### ISSUE TITLE
Verwijderen SFTP gegevens uit main.yml

### ISSUE THREAD

**Issue by marcveens** [Rowin206/webapp.gamesource.nl#3]
.github/workflows/main.yml

Ik gok dat het niet de bedoeling is dat iedereen bij deze gegevens kan, toch?

**Comment by Rowin206** [comment]
> .github/workflows/main.yml
> 
> Ik gok dat het niet de bedoeling is dat iedereen bij deze gegevens kan, toch?

Klopt! Thanks voor je oplettendheid :) Gegevens zijn iig veranderd. Ik ga de historie van de files ook meteen verwijderen.

**Comment by Rowin206** [comment]
Commits/historie verwijderd > OK
